/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=worker/.env.example --include-runtime=false` (hash: 7399b461ee7a7d58dc6fadf0c6312030)
interface __BaseEnv_Env {
	AUTH_RATE_LIMITER: RateLimit;
	MCP_RATE_LIMITER: RateLimit;
	PUBLIC_URL: "https://shopify-va-toolkit.vinceluxxe.workers.dev";
	SHOPIFY_CLIENT_ID: string;
	SHOPIFY_CLIENT_SECRET: string;
	CONNECTOR_STORAGE_KEY: string;
	OAUTH_ISSUER: DurableObjectNamespace<import("./worker/index").OAuthIssuer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "OAuthIssuer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_URL" | "SHOPIFY_CLIENT_ID" | "SHOPIFY_CLIENT_SECRET" | "CONNECTOR_STORAGE_KEY">> {}
}
